FROM ubuntu:22.04

RUN apt update && apt install -y \
	desktop-file-utils \
	libglib2.0-dev \
	build-essential \
	zlib1g-dev \
	libgtk-3-dev \
	libwebkit2gtk-4.0-dev \
	wget \
	patchelf \
	file \
	fuse

WORKDIR /bmm

